// Code generated by bin/generate.py. DO NOT EDIT.
export default {
    accountlogic: {

        Login: {
            url: 'accountlogic/login',
            type: 'post',
        },

        GetProfile: {
            url: 'accountlogic/get_profile',
            type: 'post',
        },

        SetProfile: {
            url: 'accountlogic/set_profile',
            type: 'post',
        },

    },

};
